### ISSUE TITLE
Udvidet bevægelsesfrihed uden sagsoprettelse

### ISSUE THREAD

**Issue by busstoptaktik** [SDFIdk/FIRE#284]
Forbedringsønske: Det skal være muligt at gennemføre en testberegning uden at oprette en sag.

**Comment by kbevers** [comment]
Muligvis kan klares med dokumentation af eksisterende funktionalitet

**Comment by busstoptaktik** [comment]
Ja, jeg tror det også: Man kan gå meget langt i processen uden at oprette en sag, men det har åbenbart ikke været tilstrækkeligt klart, siden denne forespørgsel kom frem

**Comment by kbevers** [comment]
Kan fx dokumenteres under i et "Kort fortalt" afsnit i manualen.
