### ISSUE TITLE
Bootstrapping af GNSS tidsserier

### ISSUE THREAD

**Issue by kbevers** [SDFIdk/FIRE#550]
Herunder et forsøg på at beskrive hvordan GNSS-tidsserier kan initieres ud fra Bernese resultatfiler. Dette er relevant både for 5D- og NKG-tidsserier, men tager udgangspunkt i førstnævnte.

Formålet er at få indlæst tidsserierne i FIRE så de efterfølgende let kan tilgås i plots og analyser. Koger man problemet ind til benet er opgaven at læse koordinater og diverse statiske mål i resultatfilerne fra Bernese og efterfølgende registrere dem som koordinater og observationer i FIRE. Herudover skal de enkelte stationers koordinater knyttes sammen i en tidsserie. Læsning af Bernesefilerne er undervejs i #540 og de første spadestik til håndtering af tidsserier er taget i #546. Især sidstnævnte er der stadig en del arbejde i. Her fokuserer vi udelukkende på registrering af koordinater og observationer.

1. Opret sag
2. Iterér over Bersenefiler, for hver GPS uge og læs filerne. For hver station* i et sæt Bernesefiler fra uge nnnn:
    1. Opret sagsevent for observationer
    2. Opret sagsevent for koordinater 
    3. Hent punktet der hører til stationen
    4. Opret `Koordinat()`
    5. Opret `Observation()`
    6. Opret `Beregning()` der knytter koordinater og observationer til hinanden. Se #549 for mere.
    7. Tilknyt `Observation` til observationssagsevent
    8. Tilknyt `Koordinat` og `Beregning` til koordinatsagsevent
    9. Indlæs de to sagsevents
4. Luk sag
5. Commit ændringer til databasen

_* Kun dem med A-flaget i Bernesefilerne_

Ovenstående forudsætter at de korrekte SRID'er er oprettet i databasen. Det er de ikke i øjeblikket, da hverken igb08 eller igb14 er registreret på nuværende tidspunkt. Jeg foreslår at de oprettes som `IGS:igb08` og `IGS:igb14`.

I det tilfælde hvor der kun er en enkelt uge at iterere over i punkt 4 er ovenstående algoritme sandsynligvis anvendelig til forlængelse af eksisterende tidsserie og kan med fordel genanvendes i program der har til formål at lagre seneste uges GNSS-koordinater fra både NKG- og 5D-beregninger.

**Comment by kbevers** [comment]
Det er muligt at det er smartere at oprette to sagsevents pr. bernesefilsæt, da vi med fordel kan inkludere de (op til) tre filer i den sagsevent hvor beregningen hører til. Der kan i princippet være uendeligt mange filer på en sagsevent men det er nok smartere hvis det begrænses.

**Comment by larsnaesbye** [comment]
Det her forudsætter at databasen i både TEST og PROD er opdateret med nyt schema, ikke?

**Comment by kbevers** [comment]
Njahe, det er nok med TEST i første omgang. Men ingen af de to databaser har fået de nye tabeller oprettet endnu. Det gør jeg formentligt snart, skal nok give besked når det sker.
