### ISSUE TITLE
Punkter med to eller flere landsnumre

### ISSUE THREAD

**Issue by ErikLysdal** [SDFIdk/FIRE#597]
Punkt 20-05-9060 kan ikke fremsøges i udstillingsmodellen, men skal søges gennem punkt 20-05-30011.
Visulet eller i fikspunktsbeskrivelsen fremgår det heller ikke at punktet har to landsnumre.

Punktet er TGBM punkt for DMIs vandstandsmåler i Ballen Havn.

**Comment by kbevers** [comment]
Med nedenstående SQL kan samtlige punkter der har to eller flere landsnumre tilknyttet fremsøges:

```
SELECT *
FROM (
    SELECT punktid, tekst, count(*) OVER (PARTITION BY punktid) ct
    FROM punktinfo 
    WHERE infotypeid=346 AND registreringtil IS NULL
    )
WHERE ct > 1;
```

Der er 1570 punkter der har to ellere flere landsnumre. Langt de fleste har to, en del har tre og otte punkter har fire landsnumre tilknyttet sig. Alt i alt 3211 landsnumre der skal tages stilling til.

Mange af dem skylles at der er i REFGEO-tiden er blevet bestilt numre fra et forkert opmålingsdistrikt, men det er ikke en generel beskrivelse af problemet. 

Vedhæftet er en oversigt over punkterne med landsnummerdupletter. Det giver et første umiddelbart overblik, men det står ikke klart hvad der er den nemmeste måde at rydde op i data på. Antallet af berørte punkter er tilpas stort til at det nok fordrer en vis automatisering.

Konsekvenserne ved en oprydning skal overvejes inden den udføres. Det vil med stor sandsynlighed skabe problemer i udstillingsmodellen. En mulig løsning er at køre en nyt totaloverførsel, hvilket dog vil nulstille al historik der kan tilgås via Datafordeleren.

[fire_prod_landsnr_dupletter.xlsx](https://github.com/SDFIdk/FIRE/files/10259699/fire_prod_landsnr_dupletter.xlsx)

**Comment by kbevers** [comment]
@chntj det er denne her problemstilling du skal kigge på. Som beskrevet ovenfor har vi en del fikspunkter der af forskellige årsager har fået to eller flere landsnumre. Altså navnene på fikspunkterne. Det er meningen at der kun skal være et landsnummer, så det er noget bøvl at nogle punkter har flere. Det skal vi have ryddet op i. Til en start er din opgave at bestemme hvilke numre der skal beholdes og hvilke der skal smides ud. Til det har jeg lavet en opdateret version af regnearket ovenfor, hvor der er indsat en kolonne til at angive hvilke numre vi skal beholde. Download det [her](https://github.com/SDFIdk/FIRE/files/10433938/fire_prod_landsnr_dupletter.xlsx). Sæt kryds ud for dem der skal beholdes. Kun et kryds for hvert sæt af punktid'er.

Hvordan vælger man så det rigtige landsnummer? Det er der nok ikke altid et entydigt svar på, men et godt bud er at kigge på løbenummeret. Altså de sidste 5 cifre i landsnummeret. Tabellen herunder kan bruges til at afgøre hvilken type fikspunkt der er tale om, og dermed også vurdere hvilket landsnummer der er det rigtige at bruge. Fikspunkterne er rangordnet efter kvalitet, sådan at GI-punkterne er "bedre" end Jessen-punkterne, der igen er bedre end højdefikspunkterne osv. 

Type | Løbenummer interval
-- | --
GI | 1-10
GI | 801-8999
Jessen | 81001-81999
Højdefikspunkt | 9001-10000
Højdefikspunkt | 19001-19999
MV-punkt | 11-799
Hjælpepunkt | 90001-99999

Her er et eksempel på to landsnumre der er tilknyttet samme punkt: `1-13-09011` og `1-13-00005`. Her vil jeg beholde det sidste fordi det er GI-nummeret der er finere end højdefikspunktsnummeret.

Måske kan du lave et smart script der kommer med et bud på hvilket landsnummer der skal beholdes. Hvis ikke det er muligt er det nok en manuel opgave med bare gå dem igennem en ad gangen.

Hvis der er punktnumre du er i tvivl om, så spørg Erik eller mig om hvilket der bør beholdes.

**Comment by kbevers** [comment]
# Punkter hvor landsnumrene har forskellige opmålingsdistrikter

Nogle punkter har landsnumre hvor der er forskel i opmålingsdistrikterne. For at finde ud af hvilket af numrene der er korrekt er man nødt til at krydskorrelere punktets position med polygoner over opmålingsdistrikterne. Polygonfilen kan hentes her: [herredsogn_fuld.zip](https://github.com/SDFIdk/FIRE/files/10435524/herredsogn_fuld.zip).

Punktets lokationskoordinat kan findes ved at slå op i fire, fx 

```
> fire info punkt 1-13-00811
--------------------------------------------------------------------------------
 PUNKT 1-13-00811
--------------------------------------------------------------------------------
  Lokation                    POINT (12.5132966388889 55.7194100222222)
  Oprettelsesdato             1700-03-01 00:00:00
  AFM:3251                    Jernrør i støbning
                              mærket krone og F.
  AFM:horisontalvertikal
  ATTR:beskrivelse            Maglegårdsallé, ca. 50 m NØ.
                              for bro i Utterslev Mose.
                              Punkt i fortov.
  ATTR:MV_punkt
  ATTR:bemærkning             Rev. 1944.
  REGION:DK
  SKITSE:png_sti              skitser_png/K-01-00901_2.png
  SKITSE:png_md5              4c563bb52828e5856e85ea0a5dd55cc5
  SKITSE:master_sti           skitser_master/K-01-00901_2.tif
  SKITSE:master_md5           25854669950af06ca205234b91644afb
  IDENT:refgeo_id             149
  IDENT:landsnr               K-01-00901
  IDENT:landsnr               1-13-00811

--- GRAFIK ---
Skitse                        K-01-00901.png

--- KOORDINATER ---
* 1989-09-14 12:00  EPSG:4258       t 12.5132966389, 55.7194100222 (35, 35)
* 1989-09-14 12:00  DK:S34S         n 75656.8000, 145227.8000 (95, 95)
```

Lokationskoordinaten (`POINT (12.5132966388889 55.7194100222222)`) i starten af outputtet kan da plottes oven på opmålingsdistrikterne med QGIS. Til det bruges pluginet "QuickWKT". Her kan man indtaste lokationskoordinaten i WKT-format (kopieres bare direkte fra `fire`s output)

![billede](https://user-images.githubusercontent.com/13132571/212915747-be4a8790-3749-475d-a9b5-089cfab1d4e0.png)

Herefter kan zoome til det nye punkt og se hvilket opmålingsdistrikt det falder under:
![billede](https://user-images.githubusercontent.com/13132571/212917907-745f1c1d-eb2b-47b2-9339-4510c5ba5180.png). Du skal formenligt lige sætte koordinatsystemet til EPSG:4326 i QGIS for at få de to lag til at passe sammen.

**Comment by kbevers** [comment]
Opdateret udtræk af landsnumrene, denne gang med koordinater: 
[fire_prod_landsnr_dupletter_med_koordinater.xlsx](https://github.com/SDFIdk/FIRE/files/10487773/fire_prod_landsnr_dupletter_med_koordinater.xlsx)

Lavet med følgende SQL:
```
SELECT a.*, g.geometri.sdo_point.x x, g.geometri.sdo_point.y y
FROM (
    SELECT pi.punktid, pi.tekst, count(*) OVER (PARTITION BY punktid) ct
    FROM punktinfo pi
    WHERE pi.infotypeid=346 AND pi.registreringtil IS NULL
    ) a
LEFT JOIN geometriobjekt g ON a.punktid=g.punktid
WHERE a.ct > 1 AND g.registreringtil IS NULL;
```

**Comment by chntj** [comment]
@kbevers Er næsten færdig med at sortere, men er stødt på to cases hvor der ikke kan bestemmes hvilket punkt der skal vælges. Excel-filen viser hvilke punktnumre der beholdes, hvor "BEHOLD" er markeret  med "1" hvis det skal beholdes og "0" hvis ikke. Special cases er markeret med "x". [beholdte_punkter.csv](https://github.com/SDFIdk/FIRE/files/10517596/beholdte_punkter.csv)

1. Der er ~50 punkter der har forskellige sogn-nr men ingen koordinater. Derfor kan man ikke tjekke i QGIS hvilket sogn punktet tilhører. I excel-filen er de markeret med "x" i "BEHOLD". Det gælder fx punktet 33-10-09010. 

2. Derudover er der løbenumre som ikke er kategoriseret i prioritetslisten. Fx 97-01-30010. Er dette nr værre eller bedre end 97-01-09088? I excel-filen har de fået kategori KAT="-1".

**Comment by kbevers** [comment]
> Der er ~50 punkter der har forskellige sogn-nr men ingen koordinater. Derfor kan man ikke tjekke i QGIS hvilket sogn punktet tilhører. I excel-filen er de markeret med "x" i "BEHOLD". Det gælder fx punktet 33-10-09010.

Så vidt jeg kan se er punkerne uden koordinater allesammen tabtgåede. Behold dem begge.

> Derudover er der løbenumre som ikke er kategoriseret i prioritetslisten. Fx 97-01-30010. Er dette nr værre eller bedre end 97-01-09088? I excel-filen har de fået kategori KAT="-1".

I de tilfælde synes jeg bare du skal vælge det laveste løbenummer. Jeg har kigget 5-10 stykker igennem og der umiddelbart ikke noget der taler for at det behøver være mere kompliceret end som så.

**Comment by chntj** [comment]
> Så vidt jeg kan se er punkerne uden koordinater allesammen tabtgåede. Behold dem begge.

@kbevers Super! hvad med de punkter som ikke har nogle koordinater, men har samme sogn-nummer. Skal begge punkter også gemmes i det tilfælde? Fx 40-03-00007

**Comment by kbevers** [comment]
Ja, behold dem begge

**Comment by chntj** [comment]
@kbevers @ErikLysdal 
Har lavet et udkast af de sorteret punkter. De navne som skal beholdes er markeret med "1" og dem som skal fjernes er markeret med "0" i "BEHOLD". For punkterne uden koordinater beholdes alle punktnavne.
[beholdte_punkter.csv](https://github.com/SDFIdk/FIRE/files/10577986/beholdte_punkter.csv)
Der er nogle punkter som skal kigges manuelt igennem. 

- Der er 8 punkter som ikke ligger i nogle af de angivne Herredsognområder. Derfor skal der manuelt tages stilling til punkternes navne. Disse punkter er markeret med "M" i "BEHOLD". Det gælder fx punktet 142-02-09021.
- Der er desuden et punkt med navn 33-14-00800 og 33-14-00802. 800 er ikke kategoriseret i listen, men er alligevel valgt fordi det er mindre end 802. Dette kan ændres.

**Comment by kbevers** [comment]
@chntj Tak, det ser rigtigt godt ud. Jeg har fået et par tips fra Lars Hole som kan bruges til at fjerne de sidste tvivlsspørgsmål. Jeg tager den her fra :-)

De næste skridt er:

- [ ] Udvikle script der med afsæt i Christinas liste kan afregistrere de overflødige landsnumre
- [ ] Prøve scriptet af på test-databasen
- [ ] Verificere at ændringerne slår igennem i Databanken
- [ ] Hvis ovenstående fejler: Dialog med DAT om en løsning, potentielt et nyt total load til databanken
- [ ] Afregistrering af overfløde landsnumre på prod-databasen
- [ ] Overførsel til Databanken
- [ ] Besked til brugere om ændringer? Nok kun nødvendigt hvis der laves total load

**Comment by kbevers** [comment]
Krydskorrelation med REFGEO:

```
 SELECT 
 	a.punktid,
 	a.tekst landsnr_fire,
	regexp_replace(hr.hnr, '^0$', 'K') || '-' || lpad(hr.snr,2,'0') || '-' || lpad(hr.lbn, 5, '0') AS landsnr_refgeo,
 	a.ct antal,
 	g.geometri.sdo_point.x lon,
 	g.geometri.sdo_point.y lat
FROM (
    SELECT pi.punktid, pi.tekst, count(*) OVER (PARTITION BY punktid) ct
    FROM punktinfo pi
    WHERE pi.infotypeid=346 AND pi.registreringtil IS NULL
    ) a
LEFT JOIN geometriobjekt g ON a.punktid=g.punktid
JOIN conv_punkt cp ON cp.id=a.punktid
JOIN hvd_ref@refgeo hr ON cp.REFNR=hr.refnr
WHERE a.ct > 1 AND g.registreringtil IS NULL;
```

**Comment by kbevers** [comment]
Jeg har nu på testdatabasen afregistreret identen 20-05-30011 så det nu kun er kendt som 20-05-09060. Jeg har derudover konstateret at ændringen også overføres korrekt til Databanken(test). Jeg har nu lavet en tilsvarende ændring på prod-databasen. I morgen tidlig kan vi se om det også går godt. Hvis det gør det skal punktet være muligt at fremsøge på Valdemar via 20-05-09060 og ikke med 20-05-30011.

Jeg går nu i gang med at lave et script der kan ændre de resterende identer. Først i test-databasen, så prod.

**Comment by kbevers** [comment]
Der er ryddet op i testdatabasen nu. Hvis overførsel til Databanken ser fornuftigt ud i morgen går jeg videre til produktionsdatabasen.

Følgende script er brugt til formålet:

```python
from sqlalchemy.sql import text, select

from fire.api import FireDb
from fire.api.model import PunktInformation

firedb = FireDb(db="test")

query = text(
"""
    SELECT p.objektid FROM (
        SELECT
            a.punktid,
            a.objektid objektid,
            a.tekst landsnr_fire,
            (
                -- Det er lidt kompliceret at skabe et landsnummer ud fra info i REFGEO, dog muligt
                CASE WHEN hr.lbn=0
                THEN regexp_replace(hr.hnr, '^0$', 'K') || '-' || lpad(hr.snr,2,'0') || '-' || chr(hr.slt) || '.' || hr.suf
                ELSE regexp_replace(hr.hnr, '^0$', 'K') || '-' || lpad(hr.snr,2,'0') || '-' || lpad(hr.lbn, 5, '0')
                END
            ) AS landsnr_refgeo,
            a.ct antal
        FROM (
            SELECT pi.punktid, pi.objektid, pi.tekst, count(*) OVER (PARTITION BY punktid) ct
            FROM punktinfo pi
            WHERE pi.infotypeid=346 AND pi.registreringtil IS NULL
            ) a
        JOIN conv_punkt cp ON cp.id=a.punktid
        JOIN hvd_ref@refgeo hr ON cp.REFNR=hr.refnr
        WHERE a.ct > 1
    ) b
    JOIN PUNKTINFO p ON p.OBJEKTID=b.objektid
    WHERE 
        b.landsnr_fire <> b.landsnr_refgeo
    """
).columns(PunktInformation.objektid)

orm_sql = select(PunktInformation).from_statement(query)

til_afregistrering = []
for punktinfo in firedb.session.execute(orm_sql).scalars():
    til_afregistrering.append(punktinfo)
    

forklaring = """Lukning af landsnummerdupletter, der er skaber forvirring i udstillingsmodellen.
Se https://github.com/SDFIdk/FIRE/issues/597 for yderligere kontekst"""
sag = firedb.ny_sag(behandler="b012349", beskrivelse=forklaring)
sagsevent = sag.ny_sagsevent(
    beskrivelse="Lukning af overflødige landsnumre",
    punktinformationer_slettede=til_afregistrering,
)

firedb.indset_sagsevent(sagsevent, commit=False)
firedb.luk_sag(sag, commit=False)
firedb.session.commit()
```

**Comment by mrlarshole** [comment]
Når man opdagede at et landsnummer var forkert i forhold til lokationskoordinaten tog man et nyt(rigtigt) nummer og samtidig gjorde man det gamle nummer til ident i fald at det havde været i brug (beregning/observationer, m.m.) det gjorde det muligt at finde frem til informationer tilknyttet det gamle nummer. 
Har vi mistet det nu?

**Comment by kbevers** [comment]
> Har vi mistet det nu?

Nej. Brug `fire info punkt -H` til at se historikken for punktet:

```
> fire info punkt -H 20-05-9060
--------------------------------------------------------------------------------
 PUNKT 20-05-09060
--------------------------------------------------------------------------------
  Lokation                    POINT (10.6399669046453 55.8153546303184)
  Oprettelsesdato             1989-07-19 10:19:00
 -AFM:2712                    Bolt, VDM.
  AFM:2708                    Tøndebolt.
 -AFM:vertikal
  AFM:vertikal
  AFM:højde_over_terræn       -0.1
  ATTR:gnss_egnet
 -ATTR:beskrivelse
                              Ballen Havn, Samsø.
                              Punkt i sydmole.
                              0.11 m under molekrone.
                              5.90 m syd for midte af vandstandsmåler.
                              7.10 m S. for hjørne af betonmole.
 -ATTR:beskrivelse            Ballen Havn, Samsø.
                              Punkt i S. mole.
                              0.11 m under molekrone.
                              5.90 m S. for midte af vandstandsmåler.
                              7.10 m S. for hjørne af betonmole.

                              Kontrolpunkt til Farvandsvæsenets vandstandsmåler.
 -ATTR:beskrivelse            Ballen Havn, Samsø.
                              Punkt i S. mole.
                              0.11 m under molekrone.

                              Kontrolpunkt til vandstandsmåler, FRV.
 -ATTR:beskrivelse            Ballen Havn, Samsø.
                              Punkt i S. mole, SV side.
                              5.08 m fra NV ende.
                              Kontrolpunkt til vandstandsmåler, FRV.
 -ATTR:beskrivelse            Ballen Havn, Samsø.
                              Punkt i S. mole, SV side.
                              Kontrolpunkt til vandstandsmåler, FRV.
  ATTR:højdefikspunkt
 -ATTR:bemærkning             Punkt oprettet
 -ATTR:bemærkning
 -ATTR:bemærkning             Rev. 2000 af Michael Iversen.
 -ATTR:bemærkning             Rev. uge 44 2009 NHO.
 -ATTR:bemærkning             Rev. uge 44 2009 NHO.
  REGION:DK
 -SKITSE:png_sti              skitser_png/20-05-09060_1.png
  SKITSE:png_sti              skitser_png/20-05-09060_2.png
 -SKITSE:png_md5              3eb3ab076fec28a101736a12b0c9aa13
  SKITSE:png_md5              3eb3ab076fec28a101736a12b0c9aa13
 -SKITSE:master_sti           skitser_master/20-05-09060_1.cgm
  SKITSE:master_sti           skitser_master/20-05-09060_2.svg
 -SKITSE:master_md5           0ef1cb81aaaa9399ac07f6caf69badee
  SKITSE:master_md5           197256b6d4ae21942006b03b37c95b81
  IDENT:refgeo_id             149518
  IDENT:landsnr               20-05-09060
 -IDENT:landsnr               20-05-30011
  ATTR:beskrivelse            Ballen Havn.
                              Havnevej, Syd Molen, NV. side.
                              Punkt i SV. side af betonvange.
  ATTR:bemærkning             Rev. uge 50 2021 PN.

--- GRAFIK ---
Skitse                        20-05-09060.png

--- KOORDINATER ---
* 2021-12-15 14:02  EPSG:5799       n 1.71094 (1)
. 2019-12-20 18:50  EPSG:5799       n 1.71090 (1)
. 2016-11-24 17:42  EPSG:5799       n 1.70879 (1)
. 2016-09-20 14:09  EPSG:5799       n 1.70908 (1)
. 2012-04-19 12:49  EPSG:5799       n 1.70800 (1)
. 2009-11-18 13:43  EPSG:5799       n 1.71000 (1)
. 2006-02-08 09:41  EPSG:5799       n 1.71300 (1)
. 2002-05-22 11:19  EPSG:5799       n 1.71300 (0)
. 2002-05-22 10:37  EPSG:5799       n 1.71400 (2)
* 2006-02-08 10:51  EPSG:5714       n 1.72600 (1)
. 2000-12-07 08:45  EPSG:5714       n 1.72600 (0)
. 1999-02-15 14:08  EPSG:5714       n 1.72700 (2)
. 1989-07-01 00:00  EPSG:5714       n 1.75100 (10)
```

Linjerne med `-` foran er tidligere versioner af en attribut. I terminalen er de også røde. Så her kan du se at `IDENT:landsnr 20-05-30011` er afregistreret.

**Comment by kbevers** [comment]
> Jeg har nu på testdatabasen afregistreret identen 20-05-30011 så det nu kun er kendt som 20-05-09060. Jeg har derudover konstateret at ændringen også overføres korrekt til Databanken(test). Jeg har nu lavet en tilsvarende ændring på prod-databasen. I morgen tidlig kan vi se om det også går godt. Hvis det gør det skal punktet være muligt at fremsøge på Valdemar via 20-05-09060 og ikke med 20-05-30011.

Ser ud til at være gået efter planen:

![billede](https://user-images.githubusercontent.com/13132571/220575720-e5ca1c04-924c-418f-9837-a2772b464c7e.png)

Det samme er den fulde kørsel på testdatabasen, så jeg laver samme manøvre på prod. Ændringerne bør være tilgængelige på Valdemar i morgen tidlig.

**Comment by kbevers** [comment]
Den fulde ændring er trådt i kraft og ser ud til at være gået godt. Den væsentligste effekt for brugerne af FIRE er, at de landsnumre der nu er blevet deaktiveret ikke kommer umiddelbart er til at søge frem med `fire info punkt`. Ligeledes *kan* der opstå problemer med `fire niv`-projekter hvis man har et eller flere af de deaktiverede landsnumre i brug. Tag fat i mig hvis det er tilfældet og det skaber problemer.

I [fire_prod_landsnr_dupletter_refgeo.xlsx](https://github.com/SDFIdk/FIRE/files/10812240/fire_prod_landsnr_dupletter_refgeo.xlsx) kan man se en liste over de ændrede punkter. Der er to kolonner med landsnumre. Hvor kolonnerne med landsnumre i FIRE og REFGEO er ens er det den aktuelle ident. I tilfældene hvor de ikke er ens er den fra REFGEO den rigtige og den i FIRE-kolonnen er nu deaktivet.
