### ISSUE TITLE
URL til fikspunkter på Valdemar i tjenesterne fejler.

### ISSUE THREAD

**Issue by mrlarshole** [SDFIdk/FIRE#624]
URL til fikspunkter på Valdemar i tjenesterne fejler. Der har været en viderestilling fra valdemar.kortforsyningen til valdemar. dataforsyningen
Dette er nu stoppet da kortforsyningen.dk website domænerne er i proces med at blive slettet.

Derfor skal alle url'er rettes i db så de peger på Dataforsyningen. Om det skal være både i FIRE og udstillingsmodellen eller om det er nok at det forekommer i Datafordelerens data til udstilling i tjenesterne må administratorerne vurdere. Initialload til DF forekommer uundgåeligt.

Problemet er akut og et alternativ quickfiks kunne være at lukke op for kortforsyningen.dk igen.

**Comment by kbevers** [comment]
@mrlarshole Jeg lukker lige denne og flytter den over til DAT på GitLab, så vi får registreret problemet der hvor det opstår.

**Comment by kbevers** [comment]
Nå, @Helle-Git er allerede foran og har oprettet issue der.
