### ISSUE TITLE
Opdater Pandas til version 1.4

### ISSUE THREAD

**Issue by kbevers** [SDFIdk/FIRE#625]
I Pandas version 1.4 er `append()` funktionen markeret deprecated. `concat()` foreslås som alternativ. Vi anvender `append` en del steder i niv-koden, så her skal der luges ud i kald til `append` inden pandas opdateres. Hvorvidt `concat` kan afløses `append` 1-1 ved jeg ikke.

**Comment by xidus** [comment]
Vi bør måske også undersøge, hvordan vi bruger det mest effektivt, da jeg har indtryk af, at concat laver en ny dataframe af de givne dataframes/rækker, den får.

**Comment by kbevers** [comment]
> da jeg har indtryk af, at concat laver en ny dataframe af de givne dataframes/rækker, den får

Ja, det er det den gør. Jeg tror den umiddelbare, naive løsning er at erstatte `df = df.append(nyt_data)` med noget i stil med `df = df.concat(df, nyt_data)`. Det er formentligt fint nok til en start.
