### ISSUE TITLE
Lokationskoordinatfejl i udvalgte planfikspunkter

### ISSUE THREAD

**Issue by mrlarshole** [SDFIdk/FIRE#631]
Hvad sker der her! Punktnummer 131-16-00001, 131-16-00002, 141-04-00002, 143-04-00001, 127-09-00002, 127-08-00002, 142-08-00002. Koordinaten til disse punkter i s34 er forkert i forhold til beskrivelsen. ETRS89 koordinaten ser ud til at passe.

**Comment by kbevers** [comment]
Vil du ikke uddybe med nogle eksempler?

**Comment by kbevers** [comment]
Jeg forstår stadig ikke problemet. Antag at jeg er idiot og forklar mig det ud fra det. Jeg kan på dine billeder se et sæt koordinater for hvert fikspunkt og intet i i tekstbeskrivelsen der strider imod dem.

**Comment by mrlarshole** [comment]
Hvis du ser på Valdemarbeskrivelserne for **samme** punkt bestilt med hhv. s34 og ETRS89 koordinater så ligger de forskellige steder på kortet. Læser man beskrivelsen forekommer det at ETRS89 koordinaten passer med beskrivelsen.

**Comment by kbevers** [comment]
> Det må næsten være et problem med overførslen fra FIRE til Databanken

... men det var det ikke!

Det er lokationskoordinaten den er galt med. Se nedenstående udskrift. Lokationskoordinaten er `(9.01094129347019, 54.8872352123414)` (et sted i Sønderjylland) og ETRS89-koordinaten er `(9.3395407361, 55.3813564528)` (det rigtige sted). Det er ikke utænkeligt at årsagen er den samme som i https://github.com/SDFIdk/FIRE/issues/630. Uden at have set nærmere på det vil jeg tro at der i overførslen fra REFGEO til FIRE er gået noget galt for udvalgte punkter. 

```
>fire info punkt --db=prod 131-16-00001

--------------------------------------------------------------------------------
 PUNKT 131-16-00001
--------------------------------------------------------------------------------
  Lokation                    POINT (9.01094129347019 54.8872352123414)
  Oprettelsesdato             1926-07-01 00:00:00
  AFM:3920                    Cylindrisk støbning 30x40 cm med
                              fredningsplade.
  AFM:horisontalvertikal
  AFM:højde_over_terræn       -0.5
  ATTR:beskrivelse            Gl. Højrupvej 6.
                              Punkt i dyrket mark, ca. 250 m NV. for
                              ejendom.
  ATTR:GI_punkt
  ATTR:tinglysningsnr         Sagsnummer fra Tingbogen ikke tilgængeligt. Opdatering udestår.
  ATTR:bemærkning             Rev. uge 25 1994 af Ole Christensen.
  REGION:DK
  SKITSE:png_sti              skitser_png/131-16-00001_2.png
  SKITSE:png_md5              6c63764fb638007b193092c1a1eedf6f
  SKITSE:master_sti           skitser_master/131-16-00001_2.cgm
  SKITSE:master_md5           3664515e5a11507a31a86fd67f980ad8
  IDENT:refgeo_id             503344
  IDENT:landsnr               131-16-00001
  IDENT:station               178

--- GRAFIK ---
Skitse                        131-16-00001.png

--- KOORDINATER ---
* 1977-09-22 12:56  EPSG:4258       t 9.3395407361, 55.3813564528 (35, 35)
* 1977-11-25 09:22  EPSG:23032      n 521593.9790, 6137488.5520 (20, 20)
* 1977-09-22 12:56  DK:S34J         n 275655.6720, 106014.3130 (20, 20)
```

**Comment by kbevers** [comment]
>  Uden at have set nærmere på det vil jeg tro at der i overførslen fra REFGEO til FIRE er gået noget galt for udvalgte punkter.

Et opslag i REFGEO afviser den teori. Nedenstående opslag giver koordinaten `(9.01094129347019, 54.8872352123414)`, altså samme lokationskoordinat som er registreret i FIRE.
```
SELECT l.geo_location.sdo_point.x, l.geo_location.sdo_point.y FROM loc_crd l WHERE refnr=503344;
```

En sammenligning af ETRS89-koordinater og lokationskoordinater viser at der er omkring 10 tilsvarende grove fejl. Det drejer sig om
```
K-01-00946
77-14-09002
77-14-00001
77-12-09004
143-04-00001
142-08-00002
141-04-00002
131-16-00002
131-16-00001
130-03-09059
127-09-00002
127-08-00002
112-02-09065
```

Punkter med lokationskoordinater der afviger fra ETRS89-koordinaten kan fx findes med
```
SELECT * FROM 
	(SELECT 
		go.punktid, 
		go.geometri.sdo_point.x gx, 
		k.x kx, 
		go.geometri.sdo_point.y gy,
		k.y ky, 
		sqrt(power(go.geometri.sdo_point.x-k.x,2) + power(go.geometri.sdo_point.y-k.y,2)) dist,
		k.transformeret
	FROM geometriobjekt go
	JOIN koordinat k ON go.punktid=k.punktid
	WHERE go.registreringtil IS NULL AND k.registreringtil IS NULL AND k.sridid=2
	)
WHERE dist > 0.001 -- forskelle på ~100 m eller mere
;
```
hvor tolerancen kan justeres efter behov. Sættes den til 0.000001 finder vi afvigelser større end cirka 10 cm, hvilket summerer til 219 alt i alt. Heraf udviser ca 75 punkter forskelle på ~1 meter og resten er forskelle mellem 1 m og 10 m. Totalt set er der cirka 5000 punkter hvor ETRS89-koordinaten og lokationskoordinaten afviger fra hinanden (vi er nede i floating point støjen for 95% eller flere af dem).

Konklusionen må være at generelt set er lokationskoordinaterne for punkter med ETRS89-koordinater gode men enkelte afviger markant og ~200 er på grænsen til at man kan lokalisere dem med lokationskoordinaten alene.

**Comment by kbevers** [comment]
Fejl rettet i databasen for de punkter hvor det så værst ud. Herunder punktvis oversigt over fejlenes størrelse (output fra `fire niv ilæg-revision`):

```
    ADVARSEL: Ny lokationskoordinat for 112-02-09065 afviger 64 m fra den gamle
    ADVARSEL: Ny lokationskoordinat for 127-08-00002 afviger 72156 m fra den gamle
    ADVARSEL: Ny lokationskoordinat for 127-09-00002 afviger 66123 m fra den gamle
    ADVARSEL: Ny lokationskoordinat for 130-03-09059 afviger 152 m fra den gamle
    ADVARSEL: Ny lokationskoordinat for 131-16-00002 afviger 58909 m fra den gamle
    ADVARSEL: Ny lokationskoordinat for 142-08-00002 afviger 60601 m fra den gamle
    ADVARSEL: Ny lokationskoordinat for 77-12-09004 afviger 126011 m fra den gamle
    ADVARSEL: Ny lokationskoordinat for 77-14-00001 afviger 152 m fra den gamle
    ADVARSEL: Ny lokationskoordinat for 77-14-09002 afviger 152 m fra den gamle
    ADVARSEL: Ny lokationskoordinat for K-01-00946 afviger 5552 m fra den gamle
```

Opdateringer bør kunne ses i Valdemar fra i morgen.
