### ISSUE TITLE
Lokationskoordinater forkerte

### ISSUE THREAD

**Issue by mrlarshole** [SDFIdk/FIRE#641]
Hej.
 
I forbindelse med nivellering i Stige ved Odense, har vi opdaget at fixpunktnummer 36-03-09054 er afbilledet forkert på jeres hjemmeside. Den er beskrevet, og sidder på Høstlyngen 43, men  grafisk er den afbilledet på Vårlyngen 43. Det gør den temmelig vanskelig at finde 😊
 

Med venlig hilsen

Jimmi Jensen
Forsyningsmedarbejder

**Comment by mrlarshole** [comment]
Har ikke kigget efter i DB men det tyder på sjusk ved digitalisering.

**Comment by kbevers** [comment]
> Har ikke kigget efter i DB men det tyder på sjusk ved digitalisering.

Det sker jo. Vil du ikke finde den korrekte koordinat så vi kan få rettet op på det?

**Comment by mrlarshole** [comment]
Databasen er nu opdateret med de rigtige koordinater
