### ISSUE TITLE
fire niv udtræk-observationer: Udtræk kun observationer mellem de efterspurgte punkter

### ISSUE THREAD

**Issue by ErikLysdal** [SDFIdk/FIRE#652]
Når eksisterende FIRE observationer udtrækkes gennem kommandoen: fire niv udtræk-observationer, kan der udtrækkes via geometrifil eller landsnumre. Dette ønske vedrører udelukkende udtræk gennem landsnumre og en anden løsning kan være gældende for geografisk udtræk.

Ved udtræk gennem specificering af landsnumrene, bør det være muligt kun at udtrække observationer mellem angivne punkter f.eks: 
![billede](https://user-images.githubusercontent.com/78030283/203796761-8872c4a7-9ced-4139-b72e-10afbde51952.png)
hvor der i version 1.5.0 også indlæses observationer til omkring liggende punkter f.eks. mellem G.I.2100 og K-75-9094.
![billede](https://user-images.githubusercontent.com/78030283/203798540-8171b922-4df0-4b66-bbdf-5afcf58a3321.png)

Der er sikkert tilfælde, hvor man ønsker at medtage andre observationer end blot direkte mellem punkterne f.eks. hvis de er nogle punkter, som er tabtgåede og erstattet af et nyt punkt på næsten samme lokation.

Vil det være muligt, at der i udtræk-observationer kommandoen medtages en option, så der default udelukkende udtrækkes observationer mellem punkterne og med en [OPTION] kan alle observationer udtrækkes, hvor et punktet er målt enten til eller fra?

**Comment by kbevers** [comment]
Det er et godt forslag. Umiddelbart ser det ikke super vanskeligt ud at lave sådan en ændring.
