### ISSUE TITLE
Fejl ved ilæg-revision.

### ISSUE THREAD

**Issue by jsnSDFE** [SDFIdk/FIRE#657]
Får denne fejl når jeg prøver at opdatere Fredericia Vest:
Nogen idéer til hvordan jeg løser dette? Har været igennem arket, og alt ser umiddelbart ud som det skal.

![Udklip](https://user-images.githubusercontent.com/78353543/206713738-12b2feeb-8f0e-454a-8f50-ad0045711f48.PNG)

**Comment by xidus** [comment]
Det ligner noget, der er løst med #638 .

Prøv at se, om du har fået kopieret et kolonnenavn over, så der er dubletter. Dette vil medføre, at kolonnenavnene ikke matcher dét, som programmet forventer, at der skal være i arket.

Løsningen, der er kommet med ovennævnte ændring, er at checke, om dette er tilfældet og give en bedre fejlmeddelelse til brugeren. Programmet kan dog, desværre, ikke se, hvilke kolonner, der ikke matcher, da efterfølgende kolonner med samme navn overskriver tidligere indlæste kolonner.

Derfor kræver det fortsat en visuel inspektion af input-data, men heldigvis kun kolonne-navnene:)

Men lad os høre, om problemet er det samme:)

**Comment by xidus** [comment]
@jsnSDFE , godt nytår!

Fik du løst problemet? Og var det ovenstående, der var galt?

**Comment by jsnSDFE** [comment]
@xidus , lige over :)

Ja.
Det var, som du gættede, et kolonnenavn jeg havde fået kopiret over. Havde ikke set #638. Får lige brillerne på næste gang 👍

**Comment by xidus** [comment]
Det er helt i orden. Problemet er godt nok adresseret i den nyere version af koden, men kommunikationsvejene er flere, så jeg tager det til efterretning, at vi måske kan gøre det mere klart, hvis der er ting, der er værd at være opmærksom på. Ovennævnte kommer også med i næste release/udgave af FIRE:)
