### ISSUE TITLE
Refaktoriser `fire.cli.niv._regn`

### ISSUE THREAD

**Issue by kbevers** [SDFIdk/FIRE#664]
Koden i [`fire.cli.niv._regn`](https://github.com/SDFIdk/FIRE/blob/ee340f7087521c33c00efc4d8cf34edfd2d28747/fire/cli/niv/_regn.py) trænger til en refaktorisering. Især funktionen `gama_beregning`, der er meget tæt koblet til de regneark, som nivellementsarbejdsgangene i FIRE benytter sig af. Det er en hæmsko for videre udvikling af selve nivellementsberegningerne.

`gama_beregning` ,tager som det er nu, nogle pandas dataframes som input og returnerer tilsvarende et sæt dataframes. Funktionen bør afkobles dataframes i en specifik struktur, og i stedet tage lister (?) med tilsvarende informationer som input. Funktionen skal have et mere snævert ansvar, så den reelt set kun udfører beregningen og ikke forholder sig til hvilket in- og output format resten af applikationen har brug for. I en mere snæver udgave er `gama_beregning` begrænset til at skrive den tilhørende xml-fil, køre `gama-local` programmet, læse den resulterende gama xml fil og returnere indholdet i en neutral form (tilsvarende input data).

**Comment by kbevers** [comment]
Hermed en hurtig guide til hvordan en simpel beregning kan sættes op og udføres med `fire`:

```
# opret en ny sag (gør det i en mappe lavet til formålet)
> fire niv opret-sag --db test refaktor "test med nivellementberegninger"

# Åben filen "refaktor.xlsk" og find fanebladet "punktoversigt". Her sættes kryds i "Fasthold" ud for "G.I.2367". Luk regnearket.
> fire niv udtræk-observationer --db test refaktor RDIO RDO1 -df 01-01-2015

# Lav beregning, første gang er kontrolberegning
> fire niv regn --db test refaktor 

# Åben regneark og se at der er et resultat i fanebladet "kontrolberegning".
# Lav herefter den endelige beregning (nogle gange vil man ændre fastholdte punkter)
> fire niv regn --db test refaktor 

# Se resultatet i fanebladet "endelig beregning"

**Comment by busstoptaktik** [comment]
Lukket med #691
