### ISSUE TITLE
Punkter udtrækkes til revision selvom de ligger udenfor distrikt og har andet herred-sogn nummer

### ISSUE THREAD

**Issue by ErikLysdal** [SDFIdk/FIRE#669]
Med kommandoen "fire niv udtræk-revision 2023_VEDL_AARHUS_SYD 103-04" udtrækkes der ligeledes punkter beliggende i 104-05 og skal - som udgangspunkt - ikke revideres.
![billede](https://user-images.githubusercontent.com/78030283/216282390-87fddf5a-b16d-484f-a7a3-a2df4d29e2f9.png)
Forklaring til billede: sort er kommunegrænsen og røde er grænsen mellem opmålingsdistrikterne.

De tre punkter udtrækkes med 103-04 afgrænsningen, selvom to af de tre ligger udenfor distriktet. At -9032 har forkert sogn nummer ift dets beliggenhed er en anden sag, som afklares i et andet issue.

**Comment by kbevers** [comment]
Det er et af de der *damned if you do, damned if you don't* situationer. Ved fremsøgning af punkterne ligges en buffer på 50 m omkring opmålingsdistriktet for at sikre at punkter der er digitaliseret unøjagtigt kommer med. Problemstillingen blev behandlet i https://github.com/SDFIdk/FIRE/issues/473

Mon ikke det bedste at gøre er at dokumentere opførslen, så det er tydeligt at det sker med vilje?
