### ISSUE TITLE
Fikspunkt vises i Valdemar , men er ikke i FIRE - og omvendt

### ISSUE THREAD

**Issue by kristiankeller** [SDFIdk/FIRE#673]
Punkt 130-04-9001 findes og vises i Valdemar:
https://valdemar.dataforsyningen.dk/FikspunktFrontend/fikspunktdetails.php?number=130-04-09001&type=Planfikspunkt&region=dk&udRefSys=25832
Men punktet findes ikke i FIRE!
Omvendt findes punkt 130-04-0001 i FIRE, men vises ikke i Valdemar..
NB der er tale om samme punkt med samme beskrivelse og koordinater.
VH Kristian

(fire) C:\>fire info punkt 130-04-0001

--------------------------------------------------------------------------------
 PUNKT MNOE
--------------------------------------------------------------------------------
  Lokation                    POINT (8.53418960833333 55.2763407527778)
  Oprettelsesdato             1927-07-01 00:00:00
  AFM:1099                    Postament.
  AFM:horisontal
  AFM:postament
  AFM:højde_over_terræn       1.3
  ATTR:gnss_egnet
  ATTR:beskrivelse            Vestervej 29 A.
                              På klittop.
  ATTR:GI_punkt
  ATTR:tinglysningsnr         Sagsnummer fra Tingbogen ikke tilgængeligt. Opdatering udestår.
  ATTR:bemærkning             Rev. uge 30 2019 ANBAR.
  NET:jessen
  REGION:DK
  SKITSE:png_sti              skitser_png/130-04-00001_4.png
  SKITSE:png_md5              0f40bb51b7db649a6df6b7af803c4a53
  SKITSE:master_sti           skitser_master/130-04-00001_4.cgm
  SKITSE:master_md5           1533483fa20739ff2e8e5d2c2cc2eb58
  IDENT:refgeo_id             497247
  IDENT:landsnr               130-04-00001
  IDENT:station               250
  IDENT:GNSS                  MNOE
  IDENT:jessen                81129

--- GRAFIK ---
Skitse                        130-04-00001.png

--- KOORDINATER ---
* 2023-01-04 16:40  EPSG:5799       n 13.23480 (1)
* 1997-12-10 13:37  EPSG:4937       n 8.5341899972, 55.2763409667, 54.05200  (20, 20, 60)
* 1976-07-23 17:14  EPSG:23032      n 470488.3700, 6125848.2931 (20, 20)
* 1976-07-14 14:27  DK:S34J         n 327001.6940, 95390.4150 (20, 20)
* 2001-07-18 15:05  DK:GM91         n 13.36200 (2)
*

**Comment by kbevers** [comment]
Det skyldes ændringer lavet i forbindelse med https://github.com/SDFIdk/FIRE/issues/597

Der har været en periode på cirka 11 timer hvor Valdemar og FIRE har været ude af trit. Fra kl. 03 i nat skulle FIRE og Valdemar (egentligt Databanken) være enige om landsnumre på *alle* punkter.

**Comment by kbevers** [comment]
Burde være løst i forbindelse med #597

**Comment by kristiankeller** [comment]
TAK - JA, nu passer FIRE med Valdemar og omvendt. 130-04-9001 er ude af systemet, hvilket er OK. DK bruger også betegnelsen 130-04-0001.
Men fint at den ”fhv. Identitet” er noteret i FIRE (med et ”-”):
  IDENT:landsnr               130-04-00001
  IDENT:station               250
-IDENT:landsnr               130-04-09001

Venlig hilsen
Kristian Keller
Geodæt, Geografiske Referencer
M. +45 2466 9570
E. ***@***.******@***.***>


Fra: Kristian Evers ***@***.***>
Sendt: 23. februar 2023 10:52
Til: SDFIdk/FIRE ***@***.***>
Cc: Kristian Keller ***@***.***>; Author ***@***.***>
Emne: Re: [SDFIdk/FIRE] Fikspunkt vises i Valdemar , men er ikke i FIRE - og omvendt (Issue #673)


Closed #673<https://github.com/SDFIdk/FIRE/issues/673> as completed.
