### ISSUE TITLE
Manglende punkter i faneblad Punktoversigt ved udtræk af observationer

### ISSUE THREAD

**Issue by Aslak-Meister** [SDFIdk/FIRE#694]
Vedhæftede excel-ark er genereret med FIRE-kommandoen nederst.

Punktnumrene 54-01-09057, 54-01-09040 samt K-64-09282 optræder i fanebladet Observationer, men mangler i fanebladet Punktoversigt. Alle tre punkter optræder kun een gang hver i fanebladet Observationer og i alle tre tilfælde som observeret til-punkt. 

Det kan forekomme, at et punkt kun er observeret som til-punkt, så det er ikke tilstrækkeligt at opstille Punktoversigt ud fra fra-punkterne (hvis det altså er det der er problemet). 

[DK.zip](https://github.com/SDFIdk/FIRE/files/11489957/DK.zip)
[asmei_temp.xlsx](https://github.com/SDFIdk/FIRE/files/11489931/asmei_temp.xlsx)

`fire niv udtræk-observationer -n P -M MTL -df 01-01-2018 -dt 01-01-2023 asmei_temp DK.geojson`

**Comment by kbevers** [comment]
@Aslak-Meister forhindrer problemet her dig i at komme videre med det du arbejder på nu?

**Comment by Aslak-Meister** [comment]
Nej, ikke på den korte bane.

**Comment by kbevers** [comment]
@ReneTandsbjerg hvorfor har du lukket dette issue?

**Comment by ReneTandsbjerg** [comment]
øh jeg troede at jeg havde åbnet noget i dette issue hvilket jeg ikke ville så derfor lukkede jeg igen.
hvad kan jeg gøre nu

**Comment by ReneTandsbjerg** [comment]
Ikke helt hjemmevant her. sorry
