### ISSUE TITLE
Forebyggelse af manglende indsættelser af observationer når nye koter indsættes...

### ISSUE THREAD

**Issue by Palle-N** [SDFIdk/FIRE#725]
Jeg kunne tænke mig at det ikke skal være muligt at indsætte nye koter uden de observationer der ligger til grund for koterne, er indsat først.

Jeg har tænkt over scenarier hvor vi skal ha´ mulighed for at indsætte nye koter uden observationerne også skal ind, og kan ikke finde noget.

Der skal stadigvæk være mulighed for at foretage ny beregning med observationer der i forvejen ligger i FIRE, og herefter kunne indsætte nye koter, men tænker ikke det er noget problem da observationerne allerede er i FIRE.

Forslaget fremsættes efter konstatering af en del manglende observationer i tidligere beregninger, hvor ny kote er indsat.

**Comment by kbevers** [comment]
Jeg har grublet over hvordan sådan en kontrol i praksis skal laves. Jeg tror det bedste vi kan gøre (uden at der skal meget udviklingstid til) er at komme med en advarsel hvis der ikke er lagt observationer i databasen i forbindelse med den sag man arbejder på.

**Comment by Palle-N** [comment]
Det kunne være en okay løsning, hvis mit forslag løber løbsk i udviklingstid...
