### ISSUE TITLE
hent_punkt kan ikke bruges til at søge efter jessennumre

### ISSUE THREAD

**Issue by krebslw** [SDFIdk/FIRE#754]
Søges efter fx punktet HVIG, som har jessennummer 81026 med `fire ts gnss 81026` fås ingen resultater, men søges med `fire ts gnss HVIG` findes to tidsserier. 
Det skyldes at hent_punkt tager det første punkt som den finder, og i mange tilfælde er det første punkt matchet på refgeo-identen når der søges på Jessennummer. 
Dette er lidt upraktisk når man arbejder med Jessennumre og tidsserier, både nu, i udviklningsøjemed, men tror også det vil være irriterende for brugeren senere hen.

**Comment by kbevers** [comment]
Kan du uddybe lidt, @krebslw? :)

**Comment by krebslw** [comment]
Ja kom til at trykke enter for tidligt!

**Comment by kbevers** [comment]
Kan løses ved at fjerne muligheden for at lave opslag på refgeonumre
